export const options = [
  { id: 7, label: "S", value: "sun" },
  { id: 1, label: "M", value: "mon" },
  { id: 2, label: "T", value: "tue" },
  { id: 3, label: "W", value: "wed" },
  { id: 4, label: "T", value: "thu" },
  { id: 5, label: "F", value: "fri" },
  { id: 6, label: "S", value: "sat" },
];
export const getCurrentYear = () => {
  return new Date().getFullYear();
};

export const OtherConst = {
  SEARCH_DEBOUNCE_TIME: 300,
};

export const convertTo12Hour = (timeString) => {
  // Split the time into hours, minutes, and seconds
  let [hours, minutes, seconds] = timeString && timeString?.split(":");

  // Convert hours from string to number
  hours = parseInt(hours);

  // Determine AM or PM
  let period = hours >= 12 ? "PM" : "AM";

  // Convert 24-hour format to 12-hour format
  hours = hours % 12 || 12; // Convert 0 to 12 for midnight

  // Return formatted time
  return `${hours}:${minutes} ${period}`;
}


export const options2 = [
  { value: "catalan", label: "Catalan" },
  { value: "danish", label: "Danish" },
  { value: "dutch", label: "Dutch" },
  { value: "faroese", label: "Faroese" },
  { value: "finnish", label: "Finnish" },
  { value: "flemish", label: "Flemish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "greek", label: "Greek" },
  { value: "icelandic", label: "Icelandic" },
  { value: "italian", label: "Italian" },
  { value: "norwegian", label: "Norwegian" },
  { value: "portuguese", label: "Portuguese" },
  { value: "swedish", label: "Swedish" },
  { value: "uk_english", label: "UK English / British English" },
  { value: "belarusian", label: "Belarusian" },
  { value: "bosnian", label: "Bosnian" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "croatian", label: "Croatian" },
  { value: "czech", label: "Czech" },
  { value: "estonian", label: "Estonian" },
  { value: "hungarian", label: "Hungarian" },
  { value: "latvian", label: "Latvian" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "macedonian", label: "Macedonian" },
  { value: "polish", label: "Polish" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "serbian", label: "Serbian" },
  { value: "slovak", label: "Slovak" },
  { value: "slovenian", label: "Slovenian" },
  { value: "turkish", label: "Turkish" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "english", label: "English" } , // Optional: keep English for consistency
  { value: "brazilian_portuguese", label: "Brazilian Portuguese" },
  { value: "canadian_french", label: "Canadian French" },
  { value: "french_creole", label: "French Creole" },
  { value: "haitian_creole", label: "Haitian Creole" },
  { value: "navajo", label: "Navajo" },
  { value: "quechua", label: "Quechua" },
  { value: "spanish", label: "Spanish" },
  { value: "amharic_ethiopia", label: "Amharic (Ethiopia)" },
  { value: "dinka_sudan", label: "Dinka (Sudan)" },
  { value: "ibo_nigeria", label: "Ibo (Nigeria)" },
  { value: "kirundi", label: "Kirundi" },
  { value: "mandinka", label: "Mandinka" },
  { value: "nuer_nilo_saharan", label: "Nuer (Nilo-Saharan)" },
  { value: "oromo_ethiopia", label: "Oromo (Ethiopia)" },
  { value: "kinyarwanda", label: "Kinyarwanda" },
  { value: "shona_zimbabwe", label: "Shona (Zimbabwe)" },
  { value: "somali", label: "Somali" },
  { value: "swahili", label: "Swahili" },
  { value: "tigrigna_ethiopia", label: "Tigrigna (Ethiopia)" },
  { value: "wolof", label: "Wolof" },
  { value: "xhosa", label: "Xhosa" },
  { value: "yoruba", label: "Yoruba" },
  { value: "zulu", label: "Zulu" },
  { value: "arabic", label: "Arabic" },
  { value: "dari", label: "Dari" },
  { value: "farsi", label: "Farsi" },
  { value: "hebrew", label: "Hebrew" },
  { value: "kurdish", label: "Kurdish" },
  { value: "pashtu", label: "Pashtu" },
  { value: "punjabi", label: "Punjabi" },
  { value: "urdu_pakistan", label: "Urdu (Pakistan)" },
  { value: "armenian", label: "Armenian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "bengali", label: "Bengali" },
  { value: "cham", label: "Cham" },
  { value: "chamorro_guam", label: "Chamorro (Guam)" },
  { value: "gujarati_india", label: "Gujarati (India)" },
  { value: "hindi", label: "Hindi" },
  { value: "indonesian", label: "Indonesian" },
  { value: "khmer_cambodia", label: "Khmer (Cambodia)" },
  { value: "kmhmu_laos", label: "Kmhmu (Laos)" },
  { value: "korean", label: "Korean" },
  { value: "laotian", label: "Laotian" },
  { value: "malayalam", label: "Malayalam" },
  { value: "malay", label: "Malay" },
  { value: "marathi_india", label: "Marathi (India)" },
  { value: "marshallese", label: "Marshallese" },
  { value: "nepali", label: "Nepali" },
  { value: "sherpa", label: "Sherpa" },
  { value: "tamil", label: "Tamil" },
  { value: "thai", label: "Thai" },
  { value: "tibetan", label: "Tibetan" },
  { value: "trukese_micronesia", label: "Trukese (Micronesia)" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "georgian", label: "Georgian" },
  { value: "kazakh", label: "Kazakh" },
  { value: "mongolian", label: "Mongolian" },
  { value: "turkmen", label: "Turkmen" },
  { value: "uzbek", label: "Uzbek" },
  { value: "amoy", label: "Amoy" },
  { value: "burmese", label: "Burmese" },
  { value: "fijian", label: "Fijian" },
  { value: "palauan", label: "Palauan" },
  { value: "samoan", label: "Samoan" },
  { value: "tongan", label: "Tongan" },
  { value: "cantonese", label: "Cantonese" },
  { value: "chinese", label: "Chinese" },
  { value: "chinese_simplified", label: "Chinese–Simplified" },
  { value: "chinese_traditional", label: "Chinese–Traditional" },
  { value: "chiu_chow", label: "Chiu Chow" },
  { value: "chow_jo", label: "Chow Jo" },
  { value: "fukienese", label: "Fukienese" },
  { value: "hakka_china", label: "Hakka (China)" },
  { value: "hmong", label: "Hmong" },
  { value: "hainanese", label: "Hainanese" },
  { value: "japanese", label: "Japanese" },
  { value: "mandarin", label: "Mandarin" },
  { value: "mien", label: "Mien" },
  { value: "shanghainese", label: "Shanghainese" },
  { value: "taiwanese", label: "Taiwanese" },
  { value: "taishanese", label: "Taishanese" },
  { value: "bikol", label: "Bikol" },
  { value: "cebuano", label: "Cebuano" },
  { value: "ilocano", label: "Ilocano" },
  { value: "ilongo", label: "Ilongo" },
  { value: "pampangan", label: "Pampangan" },
  { value: "pangasinan", label: "Pangasinan" },
  { value: "tagalog", label: "Tagalog" },
  { value: "visayan", label: "Visayan" },
  { value: "american_sign_language", label: "American Sign Language" },
  { value: "braille", label: "Braille" },
  { value: "esperanto", label: "Esperanto" },
  { value: "latin", label: "Latin" },
  { value: "phonetic", label: "Phonetic" },
  { value: "real_time_remote_captioning", label: "Real Time & Remote Captioning" },
  { value: "tactile", label: "Tactile" },
  { value: "limited_resources", label: "Limited Resources Available" }
];
